# ASSIGNMENT DAY 3

QUESTION 1

In [1]:
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

QUESTION 2

In [15]:
l1 = []
print("Enter First List")
for i in range(0,5):
    n = int(input())
    l1.append(n)
a1 = np.array(l1)
print(a1)

Enter First List
10
5
55
45
33
[10  5 55 45 33]


In [16]:
l2 = []
print("Enter Second List")
for i in range(0,5):
    m = int(input())
    l2.append(m)
a2 = np.array(l2)
print(a2)



Enter Second List
22
11
50
45
36
[22 11 50 45 36]


In [17]:
np.concatenate((a1,a2))

array([10,  5, 55, 45, 33, 22, 11, 50, 45, 36])

In [20]:
s1 = np.sort(a1)
s2 = np.sort(a2)
print(a1,"\n",a2)

[ 5 10 33 45 55] 
 [11 22 36 45 50]


QUESTION 3

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)
print("dimension \t", arr.ndim, "\n size \t", arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension 	 2 
 size 	 9


QUESTION 4

In [14]:
arr = np.arange(1,10)

print(arr.shape)

arr_2d = arr[np.newaxis]

print(arr_2d.shape)

(9,)
(1, 9)


In [17]:
x = np.zeros((3, 4)) 
y = np.expand_dims(x, axis=1).shape
print(y) 

(3, 1, 4)


QUESTION 5

In [31]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[6, 7],
              [8, 9]])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [32]:
np.hstack((a, b))

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

QUESTION 6

In [37]:
a= np.array([1, 1, 3, 4, 5, 5, 6])

np.unique(a)

array([1, 3, 4, 5, 6])

In [41]:
np.count_nonzero(np.unique(a))

5